version: '3.8'

services:
  phoenix:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      MIX_ENV: dev
      DB_USERNAME: root
      DB_PASSWORD: ""
      DB_NAME: tienda
      DB_HOST: db
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3310:3306"   # Cambiamos aquí (de 3307 a 3310)
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: tienda4
    volumes:
      - db_data:/var/lib/mysql

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "8090:8080"   # Cambiamos aquí (de 8081 a 8090)
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db_data:
  jenkins_home:
