services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: tienda
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    command: mix phx.server
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: ecto://root:123456@db/tienda
    depends_on:
      - db
    volumes:
      - .:/app

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Permite que Jenkins use Docker del host
      - ./jenkins:/var/jenkins_home  # Configuración y persistencia de Jenkins
    privileged: true  # Para garantizar que Jenkins tenga acceso completo a Docker
    environment:
      DOCKER_HOST: "unix:///var/run/docker.sock"  # Asegura que Jenkins se conecte correctamente al Docker del host

volumes:
  mysql-data:
